/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author rayan
 */
public class Main extends javax.swing.JFrame {

    private DefaultListModel histModel = new DefaultListModel();
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        historyFrame = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        liHistory = new javax.swing.JList<>();
        btHisClose = new javax.swing.JButton();
        btSimpleSearch = new javax.swing.JButton();
        btAndSearch = new javax.swing.JButton();
        btOrSearch = new javax.swing.JButton();
        btClose = new javax.swing.JButton();
        tfWords = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        liWords = new javax.swing.JList<>();
        btHistory = new javax.swing.JButton();

        jLabel2.setText("SEARCH HISTORY");

        jScrollPane2.setViewportView(liHistory);

        btHisClose.setText("Close");
        btHisClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHisCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout historyFrameLayout = new javax.swing.GroupLayout(historyFrame.getContentPane());
        historyFrame.getContentPane().setLayout(historyFrameLayout);
        historyFrameLayout.setHorizontalGroup(
            historyFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(historyFrameLayout.createSequentialGroup()
                .addGroup(historyFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btHisClose)
                    .addGroup(historyFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(historyFrameLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(historyFrameLayout.createSequentialGroup()
                            .addGap(126, 126, 126)
                            .addComponent(jLabel2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        historyFrameLayout.setVerticalGroup(
            historyFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(historyFrameLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btHisClose)
                .addGap(27, 27, 27))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Searcher");

        btSimpleSearch.setText("Simple Search");
        btSimpleSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSimpleSearchActionPerformed(evt);
            }
        });

        btAndSearch.setText("AND Search");
        btAndSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAndSearchActionPerformed(evt);
            }
        });

        btOrSearch.setText("OR Seach");
        btOrSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOrSearchActionPerformed(evt);
            }
        });

        btClose.setText("Close");
        btClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCloseActionPerformed(evt);
            }
        });

        tfWords.setForeground(new java.awt.Color(191, 186, 186));
        tfWords.setText("Feeling lucky today?");
        tfWords.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tfWords.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfWordsMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setText("Seacher");
        jLabel1.setToolTipText("");

        jScrollPane1.setViewportView(liWords);

        btHistory.setText("Search History");
        btHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHistoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btHistory)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btClose))
                    .addComponent(tfWords, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btSimpleSearch)
                                .addGap(35, 35, 35)
                                .addComponent(btAndSearch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btOrSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfWords, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSimpleSearch)
                    .addComponent(btAndSearch)
                    .addComponent(btOrSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btClose)
                    .addComponent(btHistory))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCloseActionPerformed
        // sets the label of showMessageDialog okButton to "Start" and cancelButton to "Exit"
    	UIManager.put("OptionPane.okButtonText", "Yes");
    	UIManager.put("OptionPane.cancelButtonText", "No");
        // guards the number of button pressed: 0 for Start, 1 for Exit
    	int option = JOptionPane.showConfirmDialog( null, "Do you really want to close?", "Searcher", 2 );
    	
    	// if option isn't 0 then exits of the searcher
    	if( option == 0 )
        {
            // close the application
            System.exit(0);
        }
        
        
    }//GEN-LAST:event_btCloseActionPerformed

    private void tfWordsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfWordsMouseClicked
        // if is the first click on the execution
        if( tfWords.getText().equals( "Feeling lucky today?" ) )
        {
            // sets to clean string
            tfWords.setText("");
        }
        // color of text is black now0
        tfWords.setForeground( Color.BLACK );
    }//GEN-LAST:event_tfWordsMouseClicked

    private void btSimpleSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSimpleSearchActionPerformed
        // adiciona palavra no historico
        histModel.addElement(tfWords.getText()); // stub
        
        // Objeto Searcher realiza busca
        
        // insere os retornos no JList
        
        DefaultListModel model = new DefaultListModel();
        liWords.setModel(model);
        // split na string resultante com base nos \n e adiciona cada um
        // for( String current : splitResult )
            // stub
            String current = "teste";
            model.addElement( current );
    }//GEN-LAST:event_btSimpleSearchActionPerformed

    private void btHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHistoryActionPerformed
        liHistory.setModel(histModel);
        // sets the hist frame size
        historyFrame.setSize( 356, 361 );
        // sets the frame as visible0
        historyFrame.setVisible(true);
    }//GEN-LAST:event_btHistoryActionPerformed

    private void btHisCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHisCloseActionPerformed
        // sets the frame as invisible
        historyFrame.setVisible(false);
    }//GEN-LAST:event_btHisCloseActionPerformed

    private void btAndSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAndSearchActionPerformed
        // adiciona palavra no historico
        histModel.addElement(tfWords.getText()); // stub
        
        DefaultListModel model = new DefaultListModel();
        this.liWords.setModel(model);
        
        // split na string resultante com base nos \n e adiciona cada um
        // for( String current : splitResult )
            // stub
            String current = "teste2";
            model.addElement( current );
    }//GEN-LAST:event_btAndSearchActionPerformed

    private void btOrSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOrSearchActionPerformed
        // adiciona palavra no historico
        histModel.addElement(tfWords.getText()); // stub
        
        DefaultListModel model = new DefaultListModel();
        this.liWords.setModel(model);
        
        // split na string resultante com base nos \n e adiciona cada um
        // for( String current : splitResult )
            // stub
            String current = "teste3";
            model.addElement( current );
    }//GEN-LAST:event_btOrSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAndSearch;
    private javax.swing.JButton btClose;
    private javax.swing.JButton btHisClose;
    private javax.swing.JButton btHistory;
    private javax.swing.JButton btOrSearch;
    private javax.swing.JButton btSimpleSearch;
    private javax.swing.JFrame historyFrame;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> liHistory;
    private javax.swing.JList<String> liWords;
    private javax.swing.JTextField tfWords;
    // End of variables declaration//GEN-END:variables

}
